# logging
LOGGING_JSON = 'logging.json'
TARGET_HANDLERS = ['console', ]

# flask config
CONFIG_CFG = 'config.cfg'
DEFAULT_ORION_ENDPOINT = 'DEFAULT_ORION_ENDPOINT'
DEFAULT_PORT = 'DEFAULT_PORT'

# environment variable name
LOG_LEVEL = 'LOG_LEVEL'
LISTEN_PORT = 'LISTEN_PORT'
ORION_ENDPOINT = 'ORION_ENDPOINT'
FIWARE_SERVICE = 'FIWARE_SERVICE'
MOBILE_ROBOT_SERVICEPATH = 'MOBILE_ROBOT_SERVICEPATH'
MOBILE_ROBOT_TYPE = 'MOBILE_ROBOT_TYPE'
MOBILE_ROBOT_ID = 'MOBILE_ROBOT_ID'

# fiware
DEFAULT_ORION_ENDPOINT = "http://127.0.0.1:1026"

# r_mode
MODE_NAVI = 'navi'
MODE_STANDBY = 'standby'

# r_state
STATE_WAITING = 'waiting'
STATE_GUIDING = 'guiding'
STATE_SUSPENDING = 'suspending'
STATE_RETURNING = 'returning'
