# logging
LOGGING_JSON = 'logging.json'
TARGET_HANDLERS = ['console', ]

# flask config
CONFIG_CFG = 'config.cfg'
DEFAULT_ORION_ENDPOINT = 'DEFAULT_ORION_ENDPOINT'
DEFAULT_PORT = 'DEFAULT_PORT'

# environment variable name
LOG_LEVEL = 'LOG_LEVEL'
LISTEN_PORT = 'LISTEN_PORT'
ORION_ENDPOINT = 'ORION_ENDPOINT'
FIWARE_SERVICE = 'FIWARE_SERVICE'
MOBILE_ROBOT_SERVICEPATH = 'MOBILE_ROBOT_SERVICEPATH'
MOBILE_ROBOT_TYPE = 'MOBILE_ROBOT_TYPE'
MOBILE_ROBOT_ID = 'MOBILE_ROBOT_ID'
DEST_LED_SERVICEPATH = 'DEST_LED_SERVICEPATH'
DEST_LED_TYPE = 'DEST_LED_TYPE'
DEST_LED_ID = 'DEST_LED_ID'
NEIGHBOR_RADIUS = 'NEIGHBOR_RADIUS'
LED_ON_X = 'LED_ON_X'
LED_ON_Y = 'LED_ON_Y'

# fiware
DEFAULT_ORION_ENDPOINT = "http://127.0.0.1:1026"
CMD_PENDING_STATE = "PENDING"

# r_mode
MODE_NAVI = 'navi'
MODE_STANDBY = 'standby'

# r_state
STATE_WAITING = 'waiting'
STATE_GUIDING = 'guiding'
STATE_SUSPENDING = 'suspending'
STATE_RETURNING = 'returning'
